CREATE DATABASE gepet;

CREATE TABLE USU_USUARIO (
	USU_ID VARCHAR(64),
	USU_NOME VARCHAR(50) NOT NULL,
	USU_EMAIL VARCHAR(50) NOT NULL,
	USU_SENHA VARCHAR(100),
	CONSTRAINT PK_USU_USUARIO PRIMARY KEY (USU_ID)
);

CREATE TABLE ANI_ANIMAL (
	ANI_ID VARCHAR(64) PRIMARY KEY,
	ANI_NOME VARCHAR(50) NOT NULL,
	ANI_PESO FLOAT NOT NULL,
	ANI_USU_ID VARCHAR(64) NOT NULL,
	FOREIGN KEY (ANI_USU_ID) REFERENCES USU_USUARIO(USU_ID)
);

CREATE TABLE VAC_VACINA (
	VAC_ID VARCHAR(64) PRIMARY KEY,
	VAC_NOME VARCHAR(30) NOT NULL
);

CREATE TABLE VAP_VACINA_APLICADA (
	VAP_ANI_ID VARCHAR(64),
	VAP_VAC_ID VARCHAR(64),
	CONSTRAINT PK_VAP_VACINA_APLICADA PRIMARY KEY (VAP_ANI_ID, VAP_VAC_ID),
	CONSTRAINT FK_ANI_ID FOREIGN KEY (VAP_ANI_ID) REFERENCES ANI_ANIMAL(ANI_ID),
	CONSTRAINT FK_VAC_ID FOREIGN KEY (VAP_VAC_ID) REFERENCES VAC_VACINA(VAC_ID)
);

CREATE TABLE AUT_AUTORIZACAO (
	AUT_ID VARCHAR(64) PRIMARY KEY,
	AUT_NOME VARCHAR(20)
);

CREATE TABLE USA_USUARIO_AUTORIZACAO(
	USA_USU_ID VARCHAR(64),
	USA_AUT_ID VARCHAR(64),
	CONSTRAINT FK_USA_USU_ID FOREIGN KEY (USA_USU_ID) REFERENCES USU_USUARIO(USU_ID),
	CONSTRAINT FK_USA_AUT_ID FOREIGN KEY (USA_AUT_ID) REFERENCES AUT_AUTORIZACAO(AUT_ID)
);
